### ISSUE TITLE
Open questions and to-dos

### ISSUE THREAD

**Issue by mwpastore** [mwpastore/ruby-piecewise#3]
#### Questions

- [ ] Should Enumerable#piecewise return an Enumerator if no block is given, a la `#select`, etc.?
- [ ] Should Enumerator#piecewise return a lazy enumerator if `self` is already lazy (eliminating the need for Enumerator::Lazy#piecewise)?
- [ ] Should `#piecewise` be broken into two separate methods, a la `#with_index` and `#each_with_index`?
- [ ] Should Enumerable#piecewise pass its args to `#each` or Enumerator#piecewise?

#### TODO

- [ ] Add more/better examples
- [ ] Test argument passing to Enumerable#each and Enumerator(::Lazy)#new
